

POST http://localhost:7000/user/signup
Content-Type: application/json

{
    "email":"johnd@gmail.com",
    
    "password":"12345678"
}

###
POST http://localhost:7000/user/login
Content-Type: application/json

{
    "email":"joe@gmail.com",
    "password":"12345678"
}


###

GET  http://localhost:7000/user/homepage
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiMjA1YzBmLTcxOWUtNGNjYS1hYTI5LWI5YmQzZDAxNWQ3OSIsImVtYWlsIjoiam9lQGdtYWlsLmNvbSIsIm5hbWUiOiJKb2UiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTk2NjM0MTYsImV4cCI6MTY1OTY2NzAxNn0.jwNFn3KHwnDEw2pmQXNbHdbzHorVEYVvFJCZwKJkuWw

###
GET  http://localhost:7000/user/check
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiMjA1YzBmLTcxOWUtNGNjYS1hYTI5LWI5YmQzZDAxNWQ3OSIsImVtYWlsIjoiam9lQGdtYWlsLmNvbSIsIm5hbWUiOiJKb2UiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTk2ODc2ODQsImV4cCI6MTY1OTY5MTI4NH0.AoV9eYq_Px44ZZnbyHu0HPFulebAOgInktb6rJJxWgE